"""Guess the number game!
Develop a program that simulates the game of guessing a number.
The program should start by generating a random number (between 1 and 50), allowing the player to iteratively try to guess the
number generated by the computer.
random library
( import random ).
In this library you will find two functions to generate random numbers:
• RANDOM.RANDRANGE (LININF,LIMSUP)
• RANDOM.RANDINT (LIMINF,LIMSUP)
The player has several attempts to guess the number, and after each
attempt a message like this should appear:
• “ Number is bigger ” - if the player's guess is lower than the number to guess
• “ Number is smaller ” - if the player's guess is higher than the
number to guess
• “ You got it!!!” - if the player's guess matches the number to
guess.
Other considerations:
• After 10 failed attempts the game should end, indicating the player's failure, with a message like “You have used up all 10 attempts :(
“.
• When the player gets the number right, the game should indicate the
number of attempts the player needed to get it right.
"""

import random
ale=random.randint(1,50)
resp=0
tent=1

while tent<=10:
    resp=int(input(f"Digite seu {tent}º palpite: "))
    tent=tent+1
    if resp<ale:
        print("O número é MAIOR")
    elif resp>ale:
        print("O número é MENOR")
    else:
        print(f"Parabéns! Você adivinhou o número em {tent-1} tentativas!")
        break
else:
    print("Você usou todas as 10 tentativas :(")